// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_get_by_name.sql

package database

import (
	"context"
)

const getByName = `-- name: GetByName :one
SELECT id, created_at, updated_at, name FROM users
WHERE name = $1
`

func (q *Queries) GetByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
